#pragma once
// Auto-generated by MetaParser. Do not edit.
// UIWidget BindingTraits for classes with UI_BIND_* annotations.
// Uses abstract UIDataModelBinder — zero RmlUi includes.

#include "UI/UIDataModelBinder.h"
#include "UI/Widget/UIWidgetBinding.h"
#include "..\..\Sample\15-NoitaLike\NoitaLike.h"

namespace MXRender {
namespace UI {
namespace Widget {

template<>
struct UIWidgetBindingTraits<NoitaLikeApp>
{
	static void BindDataModel(UIDataModelBinder* binder, NoitaLikeApp* data)
	{
		binder->Bind("hp", &data->m_hp);
		binder->Bind("score", &data->m_score);
		binder->Bind("wand", &data->m_wand);


	}

	static Vector<UIBindingEntry> GetBindingEntries(const rttr::type& type)
	{
		return {
			{ "hp", type.get_property("m_hp"), EBindingMode::OneWay, {} },
			{ "score", type.get_property("m_score"), EBindingMode::OneWay, {} },
			{ "wand", type.get_property("m_wand"), EBindingMode::OneWay, {} },

		};
	}

	static Map<String, Map<String, String>> GetFieldMetadata()
	{
		return {};
	}
};

} // namespace Widget
} // namespace UI
} // namespace MXRender

