#pragma once
// Auto-generated by MetaParser. Do not edit.
// UIWidget BindingTraits for classes with UI_BIND_* annotations.
// Uses abstract UIDataModelBinder — zero RmlUi includes.

#include "UI/UIDataModelBinder.h"
#include "UI/Widget/UIWidgetBinding.h"
#include "..\..\Editor\UI\UIPreviewPanel\UIPreviewData.h"

namespace MXRender {
namespace UI {
namespace Widget {

template<>
struct UIWidgetBindingTraits<UIPreviewData>
{
	static void BindDataModel(UIDataModelBinder* binder, UIPreviewData* data)
	{
		binder->Bind("hp", &data->m_hp);
		binder->Bind("score", &data->m_score);
		binder->Bind("player_name", &data->m_player_name);
		binder->Bind("m_volume", &data->m_volume);

	}

	static Vector<UIBindingEntry> GetBindingEntries(const rttr::type& type)
	{
		return {
			{ "hp", type.get_property("m_hp"), EBindingMode::OneWay, {} },
			{ "score", type.get_property("m_score"), EBindingMode::OneWay, {} },
			{ "player_name", type.get_property("m_player_name"), EBindingMode::OneWay, {} },
			{ "m_volume", type.get_property("m_volume"), EBindingMode::TwoWay, {} },
		};
	}

	static Map<String, Map<String, String>> GetFieldMetadata()
	{
		return {};
	}
};

} // namespace Widget
} // namespace UI
} // namespace MXRender

