#include "network_replication_generator.h"
#include "language_types/class.h"
#include "language_types/field.h"
#include "language_types/method.h"
#include "template_manager/template_manager.h"
#include "meta/meta_info.h"
#include "meta/meta_data_config.h"

#include <iostream>
#include <fstream>
#include <sstream>
#include <filesystem>

namespace Generator
{

NetworkReplicationGenerator::NetworkReplicationGenerator(
	std::string source_directory,
	std::function<std::string(std::string)> get_include_function) :
	GeneratorInterface(source_directory + "/_Generated/Network",
		source_directory, get_include_function)
{
	m_out_path = source_directory + "/_Generated/Network";
	prepareStatus(source_directory);
}

int NetworkReplicationGenerator::generate(std::string path, SchemaMoudle schema)
{
	for (auto& class_temp : schema.classes)
	{
		// Check if this class has any network annotations
		bool has_replicate = false;
		bool has_net_class = false;
		NetClassDef def;

		// Check for NET_CLASS on the class itself
		if (class_temp->m_meta_data.have(NETCLASS))
		{
			def.class_id = (UInt16)std::stoi(class_temp->m_meta_data.Get(NETCLASS));
			has_net_class = true;
		}

		// Scan fields for REPLICATE annotations
		UInt32 bit_index = 0;
		for (auto& field : class_temp->m_fields)
		{
			if (field->m_meta_data.have(REPLICATE))
			{
				ReplicaField rf;
				rf.field_name = field->m_display_name;
				rf.bit_index = bit_index++;
				rf.condition = field->m_meta_data.Get(REPLICATE);
				rf.owner_only = field->m_meta_data.have(OWNERONLY);
				def.replicated_fields.push_back(rf);
				has_replicate = true;
			}
		}

		// Scan methods for RPC annotations
		for (auto& method : class_temp->m_methods)
		{
			if (method->m_meta_data.have(RPC))
			{
				RPCMethod rm;
				rm.method_name = method->m_name;
				rm.target = method->m_meta_data.Get(RPC);
				rm.rpc_id = m_next_rpc_id++;
				def.rpc_methods.push_back(rm);
			}
		}

		if (!has_replicate && !has_net_class && def.rpc_methods.empty()) continue;

		def.class_name = class_temp->m_name;
		def.qualified_name = class_temp->m_namespace + "::" + class_temp->m_name;
		def.property_count = (UInt32)def.replicated_fields.size();

		m_classes.push_back(std::move(def));

		// ---- Generate Replication Traits ----
		if (has_replicate)
		{
			std::string gen_file = m_out_path + "/" + class_temp->m_name + ".Replication.Gen.h";
			std::ofstream ofs(gen_file, std::ios::out | std::ios::trunc);
			if (!ofs.is_open()) continue;

			ofs << "// Auto-generated by NetworkReplicationGenerator — DO NOT EDIT\n";
			ofs << "#pragma once\n\n";
			ofs << "#include \"Network/Replication/ReplicationObject.h\"\n\n";

			// Generate ReplicationTraits<T> specialization
			ofs << "MYRENDERER_BEGIN_NAMESPACE(MXRender)\n";
			ofs << "MYRENDERER_BEGIN_NAMESPACE(Network)\n";
			ofs << "MYRENDERER_BEGIN_NAMESPACE(Replication)\n\n";

			ofs << "template<>\n";
			ofs << "struct ReplicationTraits<" << def.qualified_name << ">\n";
			ofs << "{\n";

			// Property mask constants
			for (auto& rf : def.replicated_fields)
			{
				std::string mask_name = "k" + rf.field_name + "Mask";
				ofs << "    static constexpr PropertyMask " << mask_name << " = 1 << " << rf.bit_index << ";\n";
			}
			ofs << "    static constexpr UInt32 kPropertyCount = " << def.property_count << ";\n\n";

			ofs << "    static void SerializeProperties(const " << def.qualified_name << "& obj,\n";
			ofs << "        UInt8* buf, UInt32& len, UInt32 max_len, PropertyMask mask)\n";
			ofs << "    {\n";
			ofs << "        UInt32 offset = 0;\n";
			for (auto& rf : def.replicated_fields)
			{
				ofs << "        if (mask & k" << rf.field_name << "Mask) {\n";
				ofs << "            memcpy(buf + offset, &obj." << rf.field_name << ", sizeof(obj." << rf.field_name << "));\n";
				ofs << "            offset += sizeof(obj." << rf.field_name << ");\n";
				ofs << "        }\n";
			}
			ofs << "        len = offset;\n";
			ofs << "    }\n\n";

			ofs << "    static void DeserializeProperties(" << def.qualified_name << "& obj,\n";
			ofs << "        const UInt8* data, UInt32 len, PropertyMask mask)\n";
			ofs << "    {\n";
			ofs << "        UInt32 offset = 0;\n";
			for (auto& rf : def.replicated_fields)
			{
				ofs << "        if (mask & k" << rf.field_name << "Mask) {\n";
				ofs << "            memcpy(&obj." << rf.field_name << ", data + offset, sizeof(obj." << rf.field_name << "));\n";
				ofs << "            offset += sizeof(obj." << rf.field_name << ");\n";
				ofs << "        }\n";
			}
			ofs << "    }\n\n";

			ofs << "    static PropertyMask GetDirtyMask(const " << def.qualified_name << "& obj,\n";
			ofs << "        const " << def.qualified_name << "& previous)\n";
			ofs << "    {\n";
			ofs << "        PropertyMask mask = 0;\n";
			for (auto& rf : def.replicated_fields)
			{
				ofs << "        if (memcmp(&obj." << rf.field_name << ", &previous." << rf.field_name;
				ofs << ", sizeof(obj." << rf.field_name << ")) != 0)\n";
				ofs << "            mask |= k" << rf.field_name << "Mask;\n";
			}
			ofs << "        return mask;\n";
			ofs << "    }\n";

			ofs << "};\n\n";  // close struct

			ofs << "MYRENDERER_END_NAMESPACE  // Replication\n";
			ofs << "MYRENDERER_END_NAMESPACE  // Network\n";
			ofs << "MYRENDERER_END_NAMESPACE  // MXRender\n";
			ofs.close();

			m_replication_headers.push_back(class_temp->m_name + ".Replication.Gen.h");
		}

		// ---- Generate RPC Stubs ----
		if (!def.rpc_methods.empty())
		{
			std::string stub_file = m_out_path + "/" + class_temp->m_name + ".RPCStubs.Gen.h";
			std::ofstream ofs(stub_file, std::ios::out | std::ios::trunc);
			if (!ofs.is_open()) continue;

			ofs << "// Auto-generated by NetworkReplicationGenerator — DO NOT EDIT\n";
			ofs << "#pragma once\n\n";
			ofs << "#include \"Network/RPC/RPCDispatcher.h\"\n\n";

			ofs << "MYRENDERER_BEGIN_NAMESPACE(MXRender)\n";
			ofs << "MYRENDERER_BEGIN_NAMESPACE(Network)\n";
			ofs << "MYRENDERER_BEGIN_NAMESPACE(RPC)\n";
			ofs << "MYRENDERER_BEGIN_NAMESPACE(Stubs)\n\n";

			for (auto& rm : def.rpc_methods)
			{
				ofs << "// RPC stub for " << def.qualified_name << "::" << rm.method_name;
				ofs << " (target=" << rm.target << ", id=" << rm.rpc_id << ")\n";

				// Client proxy: send
				ofs << "inline void " << def.class_name << "_" << rm.method_name << "_Send(";
				ofs << "RPCID rpc_id = " << rm.rpc_id << ")\n";
				ofs << "{\n";
				ofs << "    // Phase 4 stub: serialize args & call RPCDispatcher::SendRPC\n";
				ofs << "    // RPCDispatcher::Get().SendRPC(rpc_id, payload, len);\n";
				ofs << "}\n\n";

				// Server handler: register
				ofs << "inline void " << def.class_name << "_" << rm.method_name << "_Register(";
				ofs << def.qualified_name << "* instance)\n";
				ofs << "{\n";
				ofs << "    RPCDispatcher::Get().RegisterHandler(" << rm.rpc_id << ",\n";
				ofs << "        [instance](const UInt8* p, UInt32 len, UInt32 sid, RPCReplyFn reply) {\n";
				ofs << "            instance->" << rm.method_name << "();\n";
				ofs << "        });\n";
				ofs << "}\n\n";
			}

			ofs << "MYRENDERER_END_NAMESPACE  // Stubs\n";
			ofs << "MYRENDERER_END_NAMESPACE  // RPC\n";
			ofs << "MYRENDERER_END_NAMESPACE  // Network\n";
			ofs << "MYRENDERER_END_NAMESPACE  // MXRender\n";
			ofs.close();

			m_rpc_stub_headers.push_back(class_temp->m_name + ".RPCStubs.Gen.h");
		}
	}

	return 0;  // success
}

void NetworkReplicationGenerator::finish()
{
	// ---- Aggregate header: AllNetworkReplication.h ----
	if (!m_replication_headers.empty())
	{
		std::string agg = m_out_path + "/AllNetworkReplication.h";
		std::ofstream ofs(agg, std::ios::out | std::ios::trunc);
		if (ofs.is_open())
		{
			ofs << "// Auto-generated — aggregate network replication includes\n";
			ofs << "#pragma once\n\n";
			for (auto& h : m_replication_headers)
				ofs << "#include \"" << h << "\"\n";
			ofs.close();
		}
	}

	// ---- Aggregate header: AllNetworkStubs.h ----
	if (!m_rpc_stub_headers.empty())
	{
		std::string agg = m_out_path + "/AllNetworkStubs.h";
		std::ofstream ofs(agg, std::ios::out | std::ios::trunc);
		if (ofs.is_open())
		{
			ofs << "// Auto-generated — aggregate network RPC stub includes\n";
			ofs << "#pragma once\n\n";
			for (auto& h : m_rpc_stub_headers)
				ofs << "#include \"" << h << "\"\n";
			ofs.close();
		}
	}
}

void NetworkReplicationGenerator::prepareStatus(std::string path)
{
	std::filesystem::create_directories(m_out_path);
}

std::string NetworkReplicationGenerator::processFileName(std::string path)
{
	return path;  // Simple pass-through — the full path is constructed in generate()
}

NetworkReplicationGenerator::~NetworkReplicationGenerator() {}

} // namespace Generator
